# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://sandipmavani.tk/
title: Sandip Mavani
email: mavanisandip94@gmail.com
author: Sandip Mavani
description: > # "Wesley Wei Qian's Personal Page"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
gems:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: medium
    title: blog
    url: https://medium.com/@mavanisandip94
  - icon: envelope-o
    title: email
    url: mailto:mavanisandip94@gmail.com
  - icon: github
    title: github
    url: https://github.com/sandipmavani
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/sandipmavani
  - icon: file-pdf-o
    title: resume
    url: https://raw.githubusercontent.com/sandipmavani/sandipmavani.github.io/master/rsc/sandip.pdf

theme: jekyll-theme-cayman
